# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidHL = QtWidgets.QHBoxLayout(self.centralwidget)
        self.centralwidHL.setObjectName("centralwidHL")
        self.leftVS = QtWidgets.QSplitter(self.centralwidget)
        self.leftVS.setOrientation(QtCore.Qt.Vertical)
        self.leftVS.setObjectName("leftVS")
        self.topleftTB = QtWidgets.QToolBox(self.leftVS)
        self.topleftTB.setStyleSheet("#topleftTB{background-color:yellow;}")
        self.topleftTB.setObjectName("topleftTB")
        self.page_databases = QtWidgets.QWidget()
        self.page_databases.setGeometry(QtCore.QRect(0, 0, 248, 182))
        self.page_databases.setObjectName("page_databases")
        self.page_databasesVL = QtWidgets.QVBoxLayout(self.page_databases)
        self.page_databasesVL.setObjectName("page_databasesVL")
        self.databasesTV = QtWidgets.QTreeView(self.page_databases)
        self.databasesTV.setObjectName("databasesTV")
        self.page_databasesVL.addWidget(self.databasesTV)
        self.topleftTB.addItem(self.page_databases, "")
        self.page_datapackages = QtWidgets.QWidget()
        self.page_datapackages.setGeometry(QtCore.QRect(0, 0, 248, 182))
        self.page_datapackages.setObjectName("page_datapackages")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_datapackages)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.datapackagesTV = QtWidgets.QTreeView(self.page_datapackages)
        self.datapackagesTV.setObjectName("datapackagesTV")
        self.verticalLayout_2.addWidget(self.datapackagesTV)
        self.topleftTB.addItem(self.page_datapackages, "")
        self.page_sessions = QtWidgets.QWidget()
        self.page_sessions.setGeometry(QtCore.QRect(0, 0, 248, 182))
        self.page_sessions.setObjectName("page_sessions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_sessions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionsTV = QtWidgets.QTreeView(self.page_sessions)
        self.sessionsTV.setObjectName("sessionsTV")
        self.verticalLayout.addWidget(self.sessionsTV)
        self.topleftTB.addItem(self.page_sessions, "")
        self.botleftW = QtWidgets.QWidget(self.leftVS)
        self.botleftW.setStyleSheet("#botleftW{background-color:green;}")
        self.botleftW.setObjectName("botleftW")
        self.botleftVL = QtWidgets.QVBoxLayout(self.botleftW)
        self.botleftVL.setContentsMargins(3, 3, 3, 3)
        self.botleftVL.setObjectName("botleftVL")
        self.datatreeTV = VnTreeView(self.botleftW)
        self.datatreeTV.setObjectName("datatreeTV")
        self.botleftVL.addWidget(self.datatreeTV)
        self.centralwidHL.addWidget(self.leftVS)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 25))
        self.menubar.setObjectName("menubar")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuMetadata = QtWidgets.QMenu(self.menubar)
        self.menuMetadata.setObjectName("menuMetadata")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.miscDW = QtWidgets.QDockWidget(MainWindow)
        self.miscDW.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.miscDW.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.miscDW.setObjectName("miscDW")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.metdatalist = MetadataList(self.dockWidgetContents)
        self.metdatalist.setObjectName("metdatalist")
        self.verticalLayout_4.addWidget(self.metdatalist)
        self.miscDW.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.miscDW)
        self.actionOpen_database = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/resources/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_database.setIcon(icon)
        self.actionOpen_database.setObjectName("actionOpen_database")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/resources/system-shutdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExtract_metadata = QtWidgets.QAction(MainWindow)
        self.actionExtract_metadata.setObjectName("actionExtract_metadata")
        self.menuDatabase.addAction(self.actionOpen_database)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionQuit)
        self.menuMetadata.addAction(self.actionExtract_metadata)
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuMetadata.menuAction())

        self.retranslateUi(MainWindow)
        self.topleftTB.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topleftTB.setItemText(self.topleftTB.indexOf(self.page_databases), _translate("MainWindow", "databases"))
        self.topleftTB.setItemText(self.topleftTB.indexOf(self.page_datapackages), _translate("MainWindow", "data packages"))
        self.topleftTB.setItemText(self.topleftTB.indexOf(self.page_sessions), _translate("MainWindow", "sessions"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuMetadata.setTitle(_translate("MainWindow", "Metadata"))
        self.actionOpen_database.setText(_translate("MainWindow", "Open database"))
        self.actionOpen_database.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit program"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionExtract_metadata.setText(_translate("MainWindow", "Extract metadata"))


from tree.metadata_view import MetadataList
from tree.views import VnTreeView
from . import resources_rc
